steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/command-center:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/command-center:$COMMIT_SHA']
  
  # Deploy container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'command-center'
      - '--image=gcr.io/$PROJECT_ID/command-center:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=3'
      - '--port=8080'

# Store images in Artifact Registry
images:
  - 'gcr.io/$PROJECT_ID/command-center:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
