#!/usr/bin/env python3
"""
Report Generator
Generate penetration testing reports from scan results.

USAGE:
    python report_generator.py --input results.json --format html|md|json

EXAMPLES:
    python report_generator.py --input scan_results.json --format html -o report.html
    python report_generator.py --input findings.json --format md --template executive
    python report_generator.py --merge scan1.json scan2.json --format html
"""

import sys
import os
import argparse
import json
from datetime import datetime
sys.path.insert(0, '/home/l0ve/Desktop/WD/Tools')
from lib import success, error, warning, info, banner

HTML_TEMPLATE = '''<!DOCTYPE html>
<html>
<head>
    <title>Penetration Test Report - {target}</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, sans-serif; margin: 40px; background: #f5f5f5; }}
        .container {{ max-width: 1200px; margin: 0 auto; background: white; padding: 40px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }}
        h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
        h2 {{ color: #34495e; margin-top: 30px; }}
        h3 {{ color: #7f8c8d; }}
        .severity-critical {{ color: #c0392b; font-weight: bold; }}
        .severity-high {{ color: #e74c3c; font-weight: bold; }}
        .severity-medium {{ color: #f39c12; font-weight: bold; }}
        .severity-low {{ color: #27ae60; font-weight: bold; }}
        .severity-info {{ color: #3498db; }}
        .finding {{ background: #fafafa; border-left: 4px solid #3498db; padding: 15px; margin: 15px 0; }}
        .finding-critical {{ border-left-color: #c0392b; }}
        .finding-high {{ border-left-color: #e74c3c; }}
        .finding-medium {{ border-left-color: #f39c12; }}
        .finding-low {{ border-left-color: #27ae60; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background: #3498db; color: white; }}
        tr:hover {{ background: #f5f5f5; }}
        .summary-box {{ display: inline-block; padding: 20px; margin: 10px; background: #ecf0f1; border-radius: 5px; text-align: center; }}
        .summary-number {{ font-size: 36px; font-weight: bold; }}
        code {{ background: #ecf0f1; padding: 2px 6px; border-radius: 3px; font-family: monospace; }}
        pre {{ background: #2c3e50; color: #ecf0f1; padding: 15px; border-radius: 5px; overflow-x: auto; }}
        .timestamp {{ color: #95a5a6; font-size: 14px; }}
    </style>
</head>
<body>
<div class="container">
    <h1>Penetration Test Report</h1>
    <p class="timestamp">Generated: {timestamp}</p>

    <h2>Executive Summary</h2>
    <p><strong>Target:</strong> {target}</p>
    <p><strong>Scan Date:</strong> {date}</p>

    <div class="summary-boxes">
        <div class="summary-box">
            <div class="summary-number severity-critical">{critical_count}</div>
            <div>Critical</div>
        </div>
        <div class="summary-box">
            <div class="summary-number severity-high">{high_count}</div>
            <div>High</div>
        </div>
        <div class="summary-box">
            <div class="summary-number severity-medium">{medium_count}</div>
            <div>Medium</div>
        </div>
        <div class="summary-box">
            <div class="summary-number severity-low">{low_count}</div>
            <div>Low</div>
        </div>
        <div class="summary-box">
            <div class="summary-number severity-info">{info_count}</div>
            <div>Info</div>
        </div>
    </div>

    <h2>Findings Summary</h2>
    <table>
        <tr>
            <th>ID</th>
            <th>Type</th>
            <th>Severity</th>
            <th>Description</th>
        </tr>
        {findings_table}
    </table>

    <h2>Detailed Findings</h2>
    {detailed_findings}

    <h2>Recommendations</h2>
    {recommendations}

    <hr>
    <p class="timestamp">Report generated by WebExploit Toolkit</p>
</div>
</body>
</html>'''

MD_TEMPLATE = '''# Penetration Test Report

**Target:** {target}
**Date:** {date}
**Generated:** {timestamp}

---

## Executive Summary

| Severity | Count |
|----------|-------|
| Critical | {critical_count} |
| High | {high_count} |
| Medium | {medium_count} |
| Low | {low_count} |
| Info | {info_count} |

**Total Findings:** {total_count}

---

## Findings Summary

{findings_summary}

---

## Detailed Findings

{detailed_findings}

---

## Recommendations

{recommendations}

---

*Report generated by WebExploit Toolkit*
'''


class ReportGenerator:
    def __init__(self):
        self.findings = []
        self.target = ''
        self.metadata = {}

    def load_results(self, filepath: str):
        """Load scan results from JSON file."""
        try:
            with open(filepath, 'r') as f:
                data = json.load(f)

            self.target = data.get('url', data.get('target', 'Unknown'))

            # Handle different result formats
            if 'vulnerabilities' in data:
                self.findings.extend(data['vulnerabilities'])
            elif 'findings' in data:
                self.findings.extend(data['findings'])
            elif 'results' in data:
                self.findings.extend(data['results'])
            elif isinstance(data, list):
                self.findings.extend(data)

            self.metadata.update(data)
            return True
        except Exception as e:
            error(f"Failed to load {filepath}: {e}")
            return False

    def merge_results(self, filepaths: list):
        """Merge multiple result files."""
        for fp in filepaths:
            self.load_results(fp)

    def categorize_severity(self, finding: dict) -> str:
        """Determine severity of finding."""
        severity = finding.get('severity', '').upper()

        if severity in ['CRITICAL', 'CRIT']:
            return 'critical'
        elif severity in ['HIGH', 'H']:
            return 'high'
        elif severity in ['MEDIUM', 'MED', 'M']:
            return 'medium'
        elif severity in ['LOW', 'L']:
            return 'low'
        else:
            # Infer from type
            ftype = finding.get('type', '').lower()
            if any(x in ftype for x in ['sqli', 'rce', 'ssrf', 'xxe']):
                return 'high'
            elif any(x in ftype for x in ['xss', 'lfi', 'idor']):
                return 'medium'
            elif any(x in ftype for x in ['info', 'disclosure']):
                return 'info'
            return 'info'

    def count_by_severity(self) -> dict:
        """Count findings by severity."""
        counts = {'critical': 0, 'high': 0, 'medium': 0, 'low': 0, 'info': 0}
        for finding in self.findings:
            sev = self.categorize_severity(finding)
            counts[sev] += 1
        return counts

    def generate_html(self) -> str:
        """Generate HTML report."""
        counts = self.count_by_severity()

        # Generate findings table
        table_rows = []
        for i, finding in enumerate(self.findings, 1):
            sev = self.categorize_severity(finding)
            ftype = finding.get('type', 'Unknown')
            desc = finding.get('description', finding.get('payload', str(finding)[:100]))
            table_rows.append(f'''
                <tr>
                    <td>{i}</td>
                    <td>{ftype}</td>
                    <td class="severity-{sev}">{sev.upper()}</td>
                    <td>{desc[:100]}...</td>
                </tr>
            ''')

        # Generate detailed findings
        detailed = []
        for i, finding in enumerate(self.findings, 1):
            sev = self.categorize_severity(finding)
            ftype = finding.get('type', 'Unknown')
            detailed.append(f'''
                <div class="finding finding-{sev}">
                    <h3>Finding #{i}: {ftype}</h3>
                    <p><strong>Severity:</strong> <span class="severity-{sev}">{sev.upper()}</span></p>
                    <p><strong>Details:</strong></p>
                    <pre>{json.dumps(finding, indent=2, default=str)}</pre>
                </div>
            ''')

        # Generate recommendations
        recs = self._generate_recommendations()

        return HTML_TEMPLATE.format(
            target=self.target,
            timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            date=datetime.now().strftime('%Y-%m-%d'),
            critical_count=counts['critical'],
            high_count=counts['high'],
            medium_count=counts['medium'],
            low_count=counts['low'],
            info_count=counts['info'],
            findings_table='\n'.join(table_rows),
            detailed_findings='\n'.join(detailed),
            recommendations=recs
        )

    def generate_markdown(self) -> str:
        """Generate Markdown report."""
        counts = self.count_by_severity()

        # Generate findings summary
        summary_lines = []
        for i, finding in enumerate(self.findings, 1):
            sev = self.categorize_severity(finding)
            ftype = finding.get('type', 'Unknown')
            summary_lines.append(f"| {i} | {ftype} | {sev.upper()} |")

        summary = "| ID | Type | Severity |\n|---|---|---|\n" + '\n'.join(summary_lines)

        # Generate detailed findings
        detailed = []
        for i, finding in enumerate(self.findings, 1):
            sev = self.categorize_severity(finding)
            ftype = finding.get('type', 'Unknown')
            detailed.append(f'''
### Finding #{i}: {ftype}

**Severity:** {sev.upper()}

**Details:**
```json
{json.dumps(finding, indent=2, default=str)}
```
''')

        return MD_TEMPLATE.format(
            target=self.target,
            timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            date=datetime.now().strftime('%Y-%m-%d'),
            critical_count=counts['critical'],
            high_count=counts['high'],
            medium_count=counts['medium'],
            low_count=counts['low'],
            info_count=counts['info'],
            total_count=len(self.findings),
            findings_summary=summary,
            detailed_findings='\n'.join(detailed),
            recommendations=self._generate_recommendations(markdown=True)
        )

    def _generate_recommendations(self, markdown: bool = False) -> str:
        """Generate recommendations based on findings."""
        recs = []

        finding_types = set(f.get('type', '').lower() for f in self.findings)

        if any('sqli' in t or 'sql' in t for t in finding_types):
            recs.append("Use parameterized queries/prepared statements to prevent SQL injection")

        if any('xss' in t for t in finding_types):
            recs.append("Implement proper output encoding and Content Security Policy headers")

        if any('lfi' in t or 'rfi' in t for t in finding_types):
            recs.append("Validate and sanitize file paths, use allowlists for file includes")

        if any('ssrf' in t for t in finding_types):
            recs.append("Validate and restrict URLs to trusted domains, implement network segmentation")

        if any('idor' in t for t in finding_types):
            recs.append("Implement proper authorization checks on all object references")

        if any('header' in t or 'security' in t for t in finding_types):
            recs.append("Implement security headers: HSTS, CSP, X-Frame-Options, X-Content-Type-Options")

        if any('cred' in t or 'password' in t or 'secret' in t for t in finding_types):
            recs.append("Remove hardcoded credentials, use secure secrets management")

        if not recs:
            recs.append("Review and address all identified findings based on severity")
            recs.append("Implement regular security assessments and code reviews")

        if markdown:
            return '\n'.join([f"- {r}" for r in recs])
        else:
            return '<ul>' + ''.join([f"<li>{r}</li>" for r in recs]) + '</ul>'


def main():
    parser = argparse.ArgumentParser(
        description='Report Generator',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
EXAMPLES:
    %(prog)s --input scan_results.json --format html -o report.html
    %(prog)s --input findings.json --format md --output report.md
    %(prog)s --merge scan1.json scan2.json --format html -o combined.html
        """
    )
    parser.add_argument('-i', '--input', help='Input JSON file')
    parser.add_argument('-m', '--merge', nargs='+', help='Merge multiple JSON files')
    parser.add_argument('-f', '--format', choices=['html', 'md', 'json'], default='html', help='Output format')
    parser.add_argument('-o', '--output', help='Output file')
    args = parser.parse_args()

    banner("Report Generator")

    generator = ReportGenerator()

    if args.merge:
        generator.merge_results(args.merge)
        info(f"Merged {len(args.merge)} files")
    elif args.input:
        generator.load_results(args.input)
    else:
        error("Specify --input or --merge")
        sys.exit(1)

    info(f"Total findings: {len(generator.findings)}")

    counts = generator.count_by_severity()
    info(f"Critical: {counts['critical']}, High: {counts['high']}, Medium: {counts['medium']}, Low: {counts['low']}, Info: {counts['info']}")

    # Generate report
    if args.format == 'html':
        report = generator.generate_html()
    elif args.format == 'md':
        report = generator.generate_markdown()
    else:
        report = json.dumps({
            'target': generator.target,
            'findings': generator.findings,
            'counts': counts,
            'generated': datetime.now().isoformat()
        }, indent=2, default=str)

    # Output
    if args.output:
        with open(args.output, 'w') as f:
            f.write(report)
        success(f"Report saved to {args.output}")
    else:
        print(report)


if __name__ == '__main__':
    main()
